### PR TITLE
Milestone 1

### PR DESCRIPTION
**Pull request by krittikatiwari**
In this PR I made the ER Diagram and the Schema 
this is my video like
[Url](https://www.loom.com/share/a928243877e24ce8a0d539b5548def16)
[Url2](https://www.loom.com/share/b6a5526a8f7c49ee9b9df5704f528524)

### CODE REVIEW

**Review by th3c0d3br34ker — COMMENTED** [review]
thanks @krittikatiwari for your submission. i reviewed your loom. 

the ERD and Schema were elaborate and well defined. 

I have one doubt:

Consider to merge the `UserRoles` and `Roles` entity, or am i missing a functionality which you have planned?

**Comment by krittikatiwari** [comment]
role table where I am going to decide the role for the project and userRole table where I am going to assign those roles that I have created in the role table to the user.

**Comment by th3c0d3br34ker** [comment]
if i ask you to add another role, where will it be added? in the `Roles` table or `UserRoles` table?

**Comment by krittikatiwari** [comment]
if you have to create another role then it will be added to the roles tables and if you want to assign some other roles to the user then it will be assigned to the user table but that role has to be present in the roles table.
roles table is for creating roles and the user table is for assigning that role to the user table.

**Review by th3c0d3br34ker — APPROVED** [review]

**Pull request merged**
